export PATH="/usr/local/MacGPG2/bin:$PATH"

if [[ $DEV == "true" ]]; then
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
    fpath=(/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk $fpath)
fi

# Load common profile config
source $HOME/.dotfiles/.zshrc

if which itermocil > /dev/null; then compctl -g '~/.itermocil/*(:t:r)' itermocil; fi
