#!/bin/bash

# Disable duplicate fonts
# Causes iterm to crash: https://github.com/ryanoasis/nerd-fonts/issues/258
defaults write com.apple.FontRegistry.user DisabledFonts -array "file://$HOME/Library/Fonts/Iosevka%20Term%20Thin%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Bold%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Bold"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Medium%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Medium%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Medium"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Light%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Thin%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Heavy%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Heavy%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Thin%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Bold%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Heavy%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Light%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Extralight%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Extralight%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Extralight"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Thin%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Thin"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Medium%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Medium%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Extralight%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Thin%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Bold%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Light%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Light%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Light"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Heavy%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Heavy"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Term%20Medium%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Extralight%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Light%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Bold%20Italic%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Bold-Italic"
defaults write com.apple.FontRegistry.user DisabledFonts -array-add "file://$HOME/Library/Fonts/Iosevka%20Heavy%20Oblique%20Nerd%20Font%20Complete.ttf#postscript-name=IosevkaNerdFontComplete-Oblique"
