k krew install cert-manager
k krew install config-registry
k krew install deprecations
k krew install df-pv
k krew install emit-event
k krew install evict-pod
k krew install exec-as
k krew install neat
k krew install node-restart
k krew install node-shell
k krew install prompt
k krew install ctx
k krew install konfig
k krew install ns
k krew install view-secret
